
server:
  port: 7001 #注册中心占用7001端口,冒号后面必须要有空格

spring:
  application:
    name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/




apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://192.168.10.182:8060
